application: goristock
version: mem
runtime: python
api_version: 1

handlers:
## Favion url.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

## Images files.
- url: /images
  static_dir: static/images
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

## CSS
- url: /css
  static_dir: static/css
- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

## admin_console
- url: /admin_console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

## Appstats
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  secure: always
  login: admin

- url: /ad/.*
  script: main.py
  login: admin

## For openID
- url: /_ah/login_required
  script: openid_login.py
- url: /_ah/IdUser
  script: openid_login.py
- url: /_ah/openidlogout
  script: openid_login.py
##- url: /_ah/openid.*
##  script: openid_login.py


## API
- url: /API.*
  script: main_api.py

## Mobile
- url: /m.*
  script: main_m.py

## Main WSGI
- url: .*
  script: main.py
  #secure: always
  #login: admin

inbound_services:
- xmpp_message
- mail

builtins:
- appstats: on
- admin_redirect: on
- datastore_admin: on

admin_console:
  pages:
  - url: /stats
    name: "Appstats"
  - url: /admin_console/
    name: "Admin_console"

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (tests/.*)
 )$
